### ISSUE TITLE
Module-level build settings

### ISSUE THREAD

**Issue by tindzk** [tindzk/seed#18]
Various build settings such as the resolvers, compiler versions (Scala, Scala.js, Scala Native), compiler flags and test frameworks are defined only on the project level.

- [x] Define these settings on `seed.model.Module` too
- [x] When importing projects, copy over the new settings as done in https://github.com/tindzk/seed/pull/17
- [x] `parseBuildToml` should return `Either[Codec.Error, Map[String, Build.Module]]`
- [x] Access build settings from modules instead of `seed.model.Build`
- [x] Update README

See also https://github.com/tindzk/seed/issues/15#issuecomment-510381769.

**Comment by nafg** [comment]
I just hit this. I need custom scalaOptions, because scalajs wants me to add the equivalent of (in sbt) `scalacOptions += "-P:scalajs:sjsDefinedByDefault"`.

**Comment by tindzk** [comment]
Thanks. Good to know there is a valid use case for this.

**Comment by megri** [comment]
I feel like having a go at this!

**Comment by tindzk** [comment]
Perfect. It is all yours.

While working on #29, I realised we should copy the project/module settings also to the platform-specific modules. So as part of loading the build file, this module:

```toml
[module.macros]
targets = ["jvm", "js"]
compilerDeps = [["org.scalamacros", "paradise", "2.1.1", "full"]]
```

would get translated to:

```toml
[module.macros.jvm]
compilerDeps = [["org.scalamacros", "paradise", "2.1.1", "full"]]

[module.macros.js]
compilerDeps = [["org.scalamacros", "paradise", "2.1.1", "full"]]
```

The upside is that it would simplify the generation logic because we will only have to check one module (and its dependencies).
